services:
  # 🚀 Backend API Server
  - type: web
    name: canga-backend
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Will be set manually in dashboard
      - key: JWT_SECRET
        sync: false  # Will be set manually in dashboard
      - key: GEMINI_API_KEY
        sync: false  # Will be set manually in dashboard
      - key: CLIENT_URL
        value: https://canga-frontend.onrender.com
      - key: FRONTEND_URL
        value: https://canga-frontend.onrender.com
    
  # 🎨 Frontend React App
  - type: web
    name: canga-frontend
    runtime: static
    plan: free
    region: frankfurt
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://canga-backend.onrender.com
      - key: REACT_APP_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 